package org.example.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class AsistentForm {
    private JPanel panel1;
    private JLabel iconLabel;
    private JTextArea vizualizareFiseTextArea;
    private JTextField idFisaUpdateTextField;
    private JTextField varstaPacientUpdateTextField;
    private JButton actualizareFisaButton;
    private JTextField medicUpdateTextField;
    private JTextField asistentUpdateTextField;
    private JTextField diagnosticCreateTextField;
    private JTextField tratamentCreateTextField;
    private JTextField simptomeCreateTextField;
    private JTextField varstaPacientCreateTextField;
    private JTextField medicCreateTextField;
    private JTextField asistentCreateTextField;
    private JButton creareFisaButton;
    private JTextField idFisaDeleteTextField;
    private JButton stergereFisaButton;
    private JComboBox filtrarePacientiMedicComboBox;
    private JComboBox filtrarePacientiDiagnosticComboBox;
    private JComboBox filtrarePacientiVarstaComboBox;
    private JTextArea filtrarePacientiMedicTextArea;
    private JTextArea filtrarePacientiDiagnosticTextArea;
    private JTextArea filtrarePacientiVarstaTextArea;
    private JButton LOGOUTButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-2383653));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(17, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-2383653));
        panel1.add(panel2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Castellar", Font.BOLD, 24, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-7667573));
        label1.setText("Asistent");
        panel2.add(label1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        iconLabel = new JLabel();
        iconLabel.setIcon(new ImageIcon(getClass().getResource("/images/asistent.png")));
        iconLabel.setText("");
        panel2.add(iconLabel, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-13893586));
        label2.setText("Vizualizare Fise Medicale");
        panel2.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        vizualizareFiseTextArea = new JTextArea();
        vizualizareFiseTextArea.setBackground(new Color(-2395946));
        vizualizareFiseTextArea.setForeground(new Color(-7667573));
        panel2.add(vizualizareFiseTextArea, new GridConstraints(4, 0, 13, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-13893586));
        label3.setText("Actualizare Fisa Medicala");
        panel2.add(label3, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setForeground(new Color(-7667573));
        label4.setText("ID Fisa");
        panel2.add(label4, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idFisaUpdateTextField = new JTextField();
        idFisaUpdateTextField.setBackground(new Color(-2526763));
        idFisaUpdateTextField.setForeground(new Color(-7667573));
        panel2.add(idFisaUpdateTextField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setForeground(new Color(-7667573));
        label5.setText("Varsta Pacient");
        panel2.add(label5, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        varstaPacientUpdateTextField = new JTextField();
        varstaPacientUpdateTextField.setBackground(new Color(-2526763));
        varstaPacientUpdateTextField.setForeground(new Color(-7667573));
        panel2.add(varstaPacientUpdateTextField, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setForeground(new Color(-13893586));
        label6.setText("Creare Fisa Medicala");
        panel2.add(label6, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setForeground(new Color(-7667573));
        label7.setText("Medic Apartinator");
        panel2.add(label7, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        medicUpdateTextField = new JTextField();
        medicUpdateTextField.setBackground(new Color(-2526763));
        medicUpdateTextField.setForeground(new Color(-7667573));
        panel2.add(medicUpdateTextField, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setForeground(new Color(-7667573));
        label8.setText("Asistent Apartinator");
        panel2.add(label8, new GridConstraints(10, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        asistentUpdateTextField = new JTextField();
        asistentUpdateTextField.setBackground(new Color(-2526763));
        asistentUpdateTextField.setForeground(new Color(-7667573));
        panel2.add(asistentUpdateTextField, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setBackground(new Color(-2526763));
        label9.setForeground(new Color(-7667573));
        label9.setText("Diagnostic");
        panel2.add(label9, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        diagnosticCreateTextField = new JTextField();
        diagnosticCreateTextField.setBackground(new Color(-2526763));
        diagnosticCreateTextField.setForeground(new Color(-7667573));
        panel2.add(diagnosticCreateTextField, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label10 = new JLabel();
        label10.setForeground(new Color(-7667573));
        label10.setText("Tratament");
        panel2.add(label10, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tratamentCreateTextField = new JTextField();
        tratamentCreateTextField.setBackground(new Color(-2526763));
        tratamentCreateTextField.setForeground(new Color(-7667573));
        panel2.add(tratamentCreateTextField, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label11 = new JLabel();
        label11.setForeground(new Color(-7667573));
        label11.setText("Simptome");
        panel2.add(label11, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        simptomeCreateTextField = new JTextField();
        simptomeCreateTextField.setBackground(new Color(-2526763));
        simptomeCreateTextField.setForeground(new Color(-7667573));
        panel2.add(simptomeCreateTextField, new GridConstraints(9, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label12 = new JLabel();
        label12.setForeground(new Color(-7667573));
        label12.setText("Varsta Pacient");
        panel2.add(label12, new GridConstraints(10, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        varstaPacientCreateTextField = new JTextField();
        varstaPacientCreateTextField.setBackground(new Color(-2526763));
        varstaPacientCreateTextField.setForeground(new Color(-7667573));
        panel2.add(varstaPacientCreateTextField, new GridConstraints(11, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label13 = new JLabel();
        label13.setForeground(new Color(-7667573));
        label13.setText("Medic Apartinator");
        panel2.add(label13, new GridConstraints(12, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        medicCreateTextField = new JTextField();
        medicCreateTextField.setBackground(new Color(-2526763));
        medicCreateTextField.setForeground(new Color(-7667573));
        panel2.add(medicCreateTextField, new GridConstraints(13, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label14 = new JLabel();
        label14.setForeground(new Color(-7667573));
        label14.setText("Asistent Apartinator");
        panel2.add(label14, new GridConstraints(14, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        asistentCreateTextField = new JTextField();
        asistentCreateTextField.setBackground(new Color(-2526763));
        asistentCreateTextField.setForeground(new Color(-7667573));
        asistentCreateTextField.setText("");
        panel2.add(asistentCreateTextField, new GridConstraints(15, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        creareFisaButton = new JButton();
        creareFisaButton.setBackground(new Color(-2395946));
        creareFisaButton.setForeground(new Color(-7667573));
        creareFisaButton.setText("Creare Fisa");
        panel2.add(creareFisaButton, new GridConstraints(16, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        actualizareFisaButton = new JButton();
        actualizareFisaButton.setBackground(new Color(-2526763));
        actualizareFisaButton.setForeground(new Color(-7667573));
        actualizareFisaButton.setText("Actualizare Fisa");
        panel2.add(actualizareFisaButton, new GridConstraints(12, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label15 = new JLabel();
        label15.setForeground(new Color(-13893586));
        label15.setText("Stergere Fisa");
        panel2.add(label15, new GridConstraints(13, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label16 = new JLabel();
        label16.setForeground(new Color(-7667573));
        label16.setText("ID Fisa");
        panel2.add(label16, new GridConstraints(14, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idFisaDeleteTextField = new JTextField();
        idFisaDeleteTextField.setBackground(new Color(-2526763));
        idFisaDeleteTextField.setForeground(new Color(-7667573));
        panel2.add(idFisaDeleteTextField, new GridConstraints(15, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        stergereFisaButton = new JButton();
        stergereFisaButton.setBackground(new Color(-2526763));
        stergereFisaButton.setForeground(new Color(-7667573));
        stergereFisaButton.setText("Stergere Fisa");
        panel2.add(stergereFisaButton, new GridConstraints(16, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label17 = new JLabel();
        label17.setForeground(new Color(-13893586));
        label17.setText("Filtrare Pacienti");
        panel2.add(label17, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label18 = new JLabel();
        label18.setForeground(new Color(-7667573));
        label18.setText("Medic");
        panel2.add(label18, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filtrarePacientiMedicComboBox = new JComboBox();
        filtrarePacientiMedicComboBox.setBackground(new Color(-2395946));
        filtrarePacientiMedicComboBox.setForeground(new Color(-7667573));
        panel2.add(filtrarePacientiMedicComboBox, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filtrarePacientiVarstaComboBox = new JComboBox();
        filtrarePacientiVarstaComboBox.setBackground(new Color(-2526763));
        filtrarePacientiVarstaComboBox.setForeground(new Color(-7667573));
        panel2.add(filtrarePacientiVarstaComboBox, new GridConstraints(13, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label19 = new JLabel();
        label19.setBackground(new Color(-2395946));
        label19.setForeground(new Color(-7667573));
        label19.setText("Varsta");
        panel2.add(label19, new GridConstraints(12, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filtrarePacientiMedicTextArea = new JTextArea();
        filtrarePacientiMedicTextArea.setBackground(new Color(-2395946));
        filtrarePacientiMedicTextArea.setForeground(new Color(-7667573));
        panel2.add(filtrarePacientiMedicTextArea, new GridConstraints(6, 3, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label20 = new JLabel();
        label20.setForeground(new Color(-7667573));
        label20.setText("Diagnostic");
        panel2.add(label20, new GridConstraints(8, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filtrarePacientiDiagnosticComboBox = new JComboBox();
        filtrarePacientiDiagnosticComboBox.setBackground(new Color(-2395946));
        filtrarePacientiDiagnosticComboBox.setForeground(new Color(-7667573));
        panel2.add(filtrarePacientiDiagnosticComboBox, new GridConstraints(9, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filtrarePacientiDiagnosticTextArea = new JTextArea();
        filtrarePacientiDiagnosticTextArea.setBackground(new Color(-2526763));
        filtrarePacientiDiagnosticTextArea.setForeground(new Color(-7667573));
        panel2.add(filtrarePacientiDiagnosticTextArea, new GridConstraints(10, 3, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        filtrarePacientiVarstaTextArea = new JTextArea();
        filtrarePacientiVarstaTextArea.setBackground(new Color(-2395946));
        filtrarePacientiVarstaTextArea.setForeground(new Color(-7667573));
        panel2.add(filtrarePacientiVarstaTextArea, new GridConstraints(14, 3, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        LOGOUTButton = new JButton();
        LOGOUTButton.setBackground(new Color(-2395946));
        LOGOUTButton.setForeground(new Color(-7667573));
        LOGOUTButton.setText("LOG OUT");
        panel2.add(LOGOUTButton, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panel1.add(spacer4, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
